---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 5.0.12
  values:
    persistence:
      storageClassName: nfs-client
    sidecar:
      dashboards:
        enabled: true
