---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus
    #version: 11.1.0
  values:
    server:
      persistentVolume:
        storageClass: nfs-client
